export const notifications = [
  {
    id: 1,
    title: "Contractor PO Received",
    role: "Procurement Engineer",
    desc: "Cairo Airport Terminal 3 high-mast lighting package PO submitted.",
    avatar: "ss.png",
    status: "online",
    unreadmessage: false,
    date: "10 min ago",
  },
  {
    id: 2,
    title: "Photometric Spec Approved",
    role: "Lighting Consultant",
    desc: "DIALux simulation report verified for New Capital administrative tower.",
    avatar: "ss.png",
    status: "online",
    unreadmessage: true,
    date: "1 hour ago",
  },
  {
    id: 3,
    title: "Datasheet Published",
    role: "Technical Catalog",
    desc: "Venice 30W Recessed Downlight IP54 technical datasheet is live.",
    avatar: "ss.png",
    status: "busy",
    unreadmessage: true,
    date: "3 hours ago",
  },
  {
    id: 4,
    title: "Inventory Restock Alert",
    role: "Warehouse Operations",
    desc: "Magnetic Track 48V rail extrusions restocked at Cairo fulfillment hub.",
    avatar: "ss.png",
    status: "online",
    unreadmessage: true,
    date: "Yesterday",
  },
  {
    id: 5,
    title: "Sample Batch Dispatched",
    role: "Logistics Dispatcher",
    desc: "LED Linear pendant samples dispatched to Alexandria design consultant.",
    avatar: "ss.png",
    status: "busy",
    unreadmessage: false,
    date: "2 days ago",
  },
];

export const messages = [
  {
    title: "Eng. Tarek Mostafa",
    desc: "Can you confirm color temperature options for Venice 4000K?",
    active: true,
    hasNotification: true,
    notification_count: 2,
    image: undefined,
    link: "#",
  },
  {
    title: "Hossam Lighting Consultancy",
    desc: "Looking for 150W IP65 High Bay photometrics for warehouse tender.",
    active: false,
    hasNotification: false,
    image: undefined,
    link: "#",
  },
  {
    title: "Arab Contractors Project Team",
    desc: "Delivery schedule confirmed for Monufia hospital project.",
    active: true,
    hasNotification: false,
    image: undefined,
    link: "#",
  },
  {
    title: "Eng. Mariam Sherif",
    desc: "Requesting customized 3-meter linear fixture quotation.",
    active: false,
    hasNotification: true,
    notification_count: 1,
    image: undefined,
    link: "#",
  },
];

export type Message = (typeof messages)[number];
export type Notification = (typeof notifications)[number];
